#!/bin/sh

### Kill existing processes to avoid duplicates
pkill -x sxhkd
pkill -x polybar

### Set monitor and desktops (adjust as needed)
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

### Window Settings
bspc config border_width 3
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false

### Theme (Rosé Pine Colors)
bspc config normal_border_color "#191724"
bspc config active_border_color "#ebbcba"
bspc config focused_border_color "#eb6f92"
bspc config presel_feedback_color "#31748f"

### Enable automatic window rules (floating, tiling, etc.)
bspc rule -a Gimp state=floating
bspc rule -a Thunderbird desktop=^2 follow=on
bspc rule -a mpv state=floating center=on

### Start SXHKD (Hotkey Daemon)
sxhkd &

### Start Polybar
~/.config/polybar/launch.sh &

# Set wallpaper
feh --bg-scale ~/.config/bspwm/wall.png &

### Start essential services
picom --config ~/.config/picom/picom.conf --experimental-backends &
nitrogen --restore &  # Restore wallpaper
dunst &  # Start notification daemon
nm-applet --indicator &  # Network manager
blueman-applet &  # Bluetooth manager
cbatticon &  # Battery indicator
udiskie &  # Automount drives

### Set cursor theme
xsetroot -cursor_name left_ptr

### Unclutter (hide mouse when idle)
unclutter -idle 2 &

### Keybindings for touchpad
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
